version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install -g typescript
      - npm install && cd client && npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling backend
      - npm run tsc
      - echo Building Client
      - npm run build-client
      - echo Build finished on `date`
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - node_modules/**/*
    - dist/**/*
    - dist/api/*
    - dist/services/*
    - build/**/*