version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install dependencies needed for running tests
      - npm install -g typescript
      - npm install && cd client && npm install
  build:
    commands:
      - tsc
      - npm run build-client
artifacts:
  type: zip
  files:
    - README.md
    - package.json
    - node_modules/**/*
    - dist/**/*
    - build/**/*